# Generated by Django 5.1.6 on 2026-06-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_fix_public_campaign_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(max_length=64, unique=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['last_seen_at'], name='campaigns_c_last_se_c6951a_idx')],
            },
        ),
    ]
