# Generated by Django 5.1.6 on 2026-03-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_profile_image_user_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auth Configuration',
                'verbose_name_plural': 'Auth Configuration',
            },
        ),
    ]
