# Generated by Django 5.1.6 on 2026-03-09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_type", models.CharField(choices=[("email_send", "Email Send"), ("payment_webhook_retry", "Payment Webhook Retry")], max_length=64)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("processing", "Processing"), ("succeeded", "Succeeded"), ("dead", "Dead")], default="pending", max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result_payload", models.JSONField(blank=True, default=dict)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("run_after", models.DateTimeField(default=django.utils.timezone.now)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["run_after", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="asyncjob",
            index=models.Index(fields=["status", "run_after"], name="users_async_status_a9b580_idx"),
        ),
        migrations.AddIndex(
            model_name="asyncjob",
            index=models.Index(fields=["job_type", "status", "run_after"], name="users_async_job_typ_590325_idx"),
        ),
        migrations.AddIndex(
            model_name="asyncjob",
            index=models.Index(fields=["created_at"], name="users_async_created_7c1190_idx"),
        ),
    ]
