# Generated by Django 5.1.6 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_asyncjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_session_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
