# Generated by Django 5.1.6 on 2026-04-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_terms_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications_consent_version',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
