# Generated by Django 5.1.6 on 2026-04-18 07:50

import apps.users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_asyncjob_type_web_push_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTermsStatus',
            fields=[
            ],
            options={
                'verbose_name': 'Terms Acceptance',
                'verbose_name_plural': 'Terms Acceptances',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', apps.users.managers.UserManager()),
            ],
        ),
    ]
