# Generated by Django 5.1.6 on 2026-07-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usertermsstatusadmin_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncjob',
            name='job_type',
            field=models.CharField(choices=[('email_send', 'Email Send'), ('payment_provision', 'Payment Provision'), ('payment_webhook_retry', 'Payment Webhook Retry'), ('web_push_send', 'Web Push Send')], max_length=64),
        ),
    ]
