# Generated by Django 5.1.6 on 2026-09-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=600)),
                ('icon_key', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('x', 'X'), ('facebook', 'Facebook'), ('link', 'Generic link')], default='link', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AS account category',
                'verbose_name_plural': 'AS account categories',
                'ordering': ('sort_order', 'name', 'pk'),
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='as_cat_active_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=120)),
                ('handle', models.CharField(blank=True, default='', max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('managed_by', models.CharField(blank=True, default='', max_length=160)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('status_label', models.CharField(default='Active', max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='social_accounts.socialaccountcategory')),
            ],
            options={
                'verbose_name': 'AS account',
                'verbose_name_plural': 'AS accounts',
                'ordering': ('sort_order', 'account_name', 'pk'),
                'indexes': [models.Index(fields=['category', 'is_active', 'sort_order'], name='as_acc_cat_active_sort_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'url'), name='as_acc_url_cat_uniq')],
            },
        ),
    ]
