[Definition]

actionstart = /usr/bin/env bash /usr/local/bin/streamx-nginx-denylist ensure
actionstop = true
actioncheck = test -x /usr/local/bin/streamx-nginx-denylist
actionban = /usr/bin/env bash /usr/local/bin/streamx-nginx-denylist ban <ip>
actionunban = /usr/bin/env bash /usr/local/bin/streamx-nginx-denylist unban <ip>

[Init]
