# Generated by Django 5.1.6 on 2026-03-03 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('session_type', models.CharField(choices=[('meeting', 'Meeting'), ('broadcasting', 'Broadcasting')], default='meeting', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('room_name', models.CharField(blank=True, max_length=255, unique=True)),
                ('livekit_room_name', models.CharField(blank=True, default='', max_length=255)),
                ('meeting_capacity', models.PositiveIntegerField(default=100)),
                ('max_audience', models.PositiveIntegerField(default=50000)),
                ('allow_overflow_broadcast', models.BooleanField(default=True)),
                ('stream_embed_url', models.URLField(blank=True, default='')),
                ('chat_embed_url', models.URLField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realtime_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_type', 'status', 'created_at'], name='realtime_re_session_545ad0_idx'), models.Index(fields=['host', 'status'], name='realtime_re_host_id_317251_idx'), models.Index(fields=['room_name'], name='realtime_re_room_na_caab0c_idx')],
            },
        ),
    ]
