# Generated by Django 5.1.6 on 2026-03-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimesession',
            name='livekit_egress_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='realtimesession',
            name='livekit_egress_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='realtimesession',
            name='stream_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('starting', 'Starting'), ('live', 'Live'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
