# Generated by Django 5.1.6 on 2026-03-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_realtimesession_livekit_egress_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimesession',
            name='rtmp_target_url',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
