# Generated by Django 5.1.6 on 2026-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0003_realtimesession_rtmp_target_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimesession',
            name='meeting_capacity',
            field=models.PositiveIntegerField(default=300),
        ),
    ]
