# Generated by Django 5.1.6 on 2026-03-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_alter_realtimesession_meeting_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimesession',
            name='presenter_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
