# Generated by Django 5.1.6 on 2026-03-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0005_realtimesession_presenter_user_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_capture_width', models.PositiveIntegerField(default=640)),
                ('broadcast_capture_height', models.PositiveIntegerField(default=360)),
                ('broadcast_capture_fps', models.PositiveIntegerField(default=20)),
                ('broadcast_max_video_bitrate_kbps', models.PositiveIntegerField(default=650)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Realtime Configuration',
                'verbose_name_plural': 'Realtime Configuration',
            },
        ),
    ]
