# Generated by Django 5.1.6 on 2026-03-03 16:07

from django.db import migrations


def seed_realtime_configuration(apps, schema_editor):
    RealtimeConfiguration = apps.get_model("realtime", "RealtimeConfiguration")
    if not RealtimeConfiguration.objects.filter(pk=1).exists():
        RealtimeConfiguration.objects.create(
            pk=1,
            broadcast_capture_width=640,
            broadcast_capture_height=360,
            broadcast_capture_fps=20,
            broadcast_max_video_bitrate_kbps=650,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("realtime", "0006_realtimeconfiguration"),
    ]

    operations = [
        migrations.RunPython(seed_realtime_configuration, migrations.RunPython.noop),
    ]
