# Generated by Django 5.1.6 on 2026-03-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0007_seed_realtimeconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeconfiguration',
            name='meeting_camera_capture_fps',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='realtimeconfiguration',
            name='meeting_camera_capture_height',
            field=models.PositiveIntegerField(default=720),
        ),
        migrations.AddField(
            model_name='realtimeconfiguration',
            name='meeting_camera_capture_width',
            field=models.PositiveIntegerField(default=1280),
        ),
        migrations.AddField(
            model_name='realtimeconfiguration',
            name='meeting_camera_max_video_bitrate_kbps',
            field=models.PositiveIntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='realtimeconfiguration',
            name='meeting_screen_capture_fps',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='realtimeconfiguration',
            name='meeting_screen_capture_height',
            field=models.PositiveIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='realtimeconfiguration',
            name='meeting_screen_capture_width',
            field=models.PositiveIntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='realtimeconfiguration',
            name='meeting_screen_max_video_bitrate_kbps',
            field=models.PositiveIntegerField(default=2500),
        ),
    ]
