# Generated by Django 5.1.6 on 2026-03-06 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_liveclassenrollment_status'),
        ('realtime', '0008_realtimeconfiguration_meeting_camera_capture_fps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimesession',
            name='linked_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_sessions', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='realtimesession',
            index=models.Index(fields=['linked_course', 'status'], name='realtime_re_linked__c3319d_idx'),
        ),
    ]
