# Generated by Django 5.1.6 on 2026-03-06 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_linked_live_class(apps, schema_editor):
    RealtimeSession = apps.get_model("realtime", "RealtimeSession")
    LiveClass = apps.get_model("courses", "LiveClass")

    meeting_sessions = RealtimeSession.objects.filter(
        session_type="meeting",
        linked_live_class__isnull=True,
        linked_course__isnull=False,
    ).only("id", "linked_course_id")
    for session in meeting_sessions.iterator():
        live_class = (
            LiveClass.objects.filter(linked_course_id=session.linked_course_id, is_active=True)
            .order_by("month_number", "id")
            .first()
        )
        if live_class:
            RealtimeSession.objects.filter(pk=session.pk).update(linked_live_class_id=live_class.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_liveclassenrollment_status'),
        ('realtime', '0009_realtimesession_linked_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimesession',
            name='linked_live_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_sessions', to='courses.liveclass'),
        ),
        migrations.RunPython(backfill_linked_live_class, noop_reverse),
        migrations.AddIndex(
            model_name='realtimesession',
            index=models.Index(fields=['linked_live_class', 'status'], name='realtime_re_linked__295e4d_idx'),
        ),
    ]
