# Generated by Django 5.1.6 on 2026-03-07 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0011_backfill_linked_live_class_for_broadcasts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtimeSessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_type', models.CharField(choices=[('meeting', 'Meeting'), ('broadcasting', 'Broadcasting')], default='meeting', max_length=20)),
                ('status', models.CharField(choices=[('starting', 'Starting'), ('recording', 'Recording'), ('stopping', 'Stopping'), ('completed', 'Completed'), ('failed', 'Failed')], default='starting', max_length=20)),
                ('livekit_egress_id', models.CharField(blank=True, default='', max_length=255)),
                ('output_file_path', models.CharField(blank=True, default='', max_length=1024)),
                ('output_download_url', models.URLField(blank=True, default='')),
                ('livekit_payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='realtime.realtimesession')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='realtime_recordings_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status', 'created_at'], name='realtime_re_session_ac7c56_idx'), models.Index(fields=['livekit_egress_id'], name='realtime_re_livekit_27538a_idx')],
            },
        ),
    ]
