# Generated by Django 5.1.6 on 2026-03-07 10:26

import apps.realtime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0012_realtimesessionrecording'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtimesessionrecording',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recording', 'verbose_name_plural': 'Recordings'},
        ),
        migrations.AddField(
            model_name='realtimesessionrecording',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.realtime.models.realtime_recording_upload_path),
        ),
    ]
