# Generated by Django 5.1.6 on 2026-03-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0013_alter_realtimesessionrecording_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimesession',
            name='speaker_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
