# Generated by Django 5.1.6 on 2026-03-09 09:14

from django.db import migrations, models


def infer_existing_meeting_quality_mode(apps, schema_editor):
    RealtimeConfiguration = apps.get_model("realtime", "RealtimeConfiguration")
    for config in RealtimeConfiguration.objects.all().iterator():
        is_premium = (
            (getattr(config, "meeting_camera_capture_width", 0) or 0) >= 1920
            and (getattr(config, "meeting_camera_capture_height", 0) or 0) >= 1080
            and (getattr(config, "meeting_camera_capture_fps", 0) or 0) >= 30
            and (getattr(config, "meeting_camera_max_video_bitrate_kbps", 0) or 0) >= 3200
            and (getattr(config, "meeting_screen_capture_width", 0) or 0) >= 1920
            and (getattr(config, "meeting_screen_capture_height", 0) or 0) >= 1080
            and (getattr(config, "meeting_screen_capture_fps", 0) or 0) >= 30
            and (getattr(config, "meeting_screen_max_video_bitrate_kbps", 0) or 0) >= 4500
        )
        config.meeting_quality_mode = "premium_hd" if is_premium else "low"
        config.save(update_fields=["meeting_quality_mode"])


def reset_meeting_quality_mode_low(apps, schema_editor):
    RealtimeConfiguration = apps.get_model("realtime", "RealtimeConfiguration")
    RealtimeConfiguration.objects.all().update(meeting_quality_mode="low")


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0014_realtimesession_speaker_user_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimeconfiguration',
            name='meeting_quality_mode',
            field=models.CharField(choices=[('low', 'Low'), ('premium_hd', 'Premium HD'), ('adaptive', 'Adaptive')], default='low', max_length=20),
        ),
        migrations.RunPython(infer_existing_meeting_quality_mode, reset_meeting_quality_mode_low),
    ]
