# Generated by Django 5.1.6 on 2026-03-11 05:57

from django.db import migrations, models


def clamp_existing_meeting_capacity_to_200(apps, schema_editor):
    RealtimeSession = apps.get_model("realtime", "RealtimeSession")
    RealtimeSession.objects.filter(meeting_capacity__gt=200).update(meeting_capacity=200)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0015_realtimeconfiguration_meeting_quality_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimesession',
            name='meeting_capacity',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.RunPython(clamp_existing_meeting_capacity_to_200, noop_reverse),
    ]
