# Generated by Django 5.1.6 on 2026-03-12 11:40

from django.db import migrations, models


def infer_existing_broadcast_quality_mode(apps, schema_editor):
    RealtimeConfiguration = apps.get_model("realtime", "RealtimeConfiguration")
    for config in RealtimeConfiguration.objects.all().iterator():
        width = int(getattr(config, "broadcast_capture_width", 0) or 0)
        height = int(getattr(config, "broadcast_capture_height", 0) or 0)
        fps = int(getattr(config, "broadcast_capture_fps", 0) or 0)
        bitrate = int(getattr(config, "broadcast_max_video_bitrate_kbps", 0) or 0)

        is_premium = width >= 1920 and height >= 1080 and fps >= 30 and bitrate >= 3200
        is_adaptive = width >= 1200 and height >= 700 and fps >= 22 and bitrate >= 1500

        if is_premium:
            mode = "premium_hd"
        elif is_adaptive:
            mode = "adaptive"
        else:
            mode = "low"

        config.broadcast_quality_mode = mode
        config.save(update_fields=["broadcast_quality_mode"])


def reset_broadcast_quality_mode_low(apps, schema_editor):
    RealtimeConfiguration = apps.get_model("realtime", "RealtimeConfiguration")
    RealtimeConfiguration.objects.all().update(broadcast_quality_mode="low")


def clamp_existing_max_audience_to_600(apps, schema_editor):
    RealtimeSession = apps.get_model("realtime", "RealtimeSession")
    RealtimeSession.objects.filter(max_audience__gt=600).update(max_audience=600)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("realtime", "0016_alter_realtimesession_meeting_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="realtimeconfiguration",
            name="broadcast_quality_mode",
            field=models.CharField(
                choices=[("low", "Low"), ("premium_hd", "Premium HD"), ("adaptive", "Adaptive")],
                default="low",
                max_length=20,
            ),
        ),
        migrations.RunPython(infer_existing_broadcast_quality_mode, reset_broadcast_quality_mode_low),
        migrations.AlterField(
            model_name="realtimesession",
            name="max_audience",
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.RunPython(clamp_existing_max_audience_to_600, noop_reverse),
    ]
