# Generated by Django 5.1.6 on 2026-03-12 17:20

from django.db import migrations, models


def clamp_existing_max_audience_to_500(apps, schema_editor):
    RealtimeSession = apps.get_model("realtime", "RealtimeSession")
    RealtimeSession.objects.filter(max_audience__gt=500).update(max_audience=500)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("realtime", "0017_realtimeconfiguration_broadcast_quality_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtimesession",
            name="max_audience",
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.RunPython(clamp_existing_max_audience_to_500, noop_reverse),
    ]
