# Generated by Django 5.1.6 on 2026-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0018_alter_realtimesession_max_audience_500'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimesession',
            name='obs_stream_key',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='realtimesession',
            name='stream_service',
            field=models.CharField(choices=[('alsyed_stream', 'Alsyed Stream (Browser Host Studio)'), ('obs_stream', 'Alsyed OBS Stream')], default='alsyed_stream', max_length=20),
        ),
    ]
