# Generated by Codex on 2026-04-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtime", "0019_realtimesession_obs_stream_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwncastChatIdentity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("platform_user_id", models.PositiveBigIntegerField(db_index=True)),
                ("platform_email", models.EmailField(blank=True, default="", max_length=254)),
                ("platform_full_name", models.CharField(blank=True, default="", max_length=255)),
                ("platform_role", models.CharField(blank=True, default="", max_length=40)),
                ("platform_display_name", models.CharField(blank=True, default="", max_length=120)),
                ("owncast_user_id", models.CharField(blank=True, default="", max_length=120)),
                ("owncast_display_name", models.CharField(max_length=120)),
                ("owncast_display_color", models.CharField(blank=True, default="", max_length=32)),
                ("owncast_authenticated", models.BooleanField(default=False)),
                ("access_token_hash", models.CharField(blank=True, default="", max_length=64)),
                ("launch_ip", models.CharField(blank=True, default="", max_length=64)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                ("bridge_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owncast_chat_identities",
                        to="realtime.realtimesession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owncast_chat_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Handle",
                "verbose_name_plural": "Handles",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owncast_display_name", "created_at"], name="realtime_ow_owncast_1cdd01_idx"),
                    models.Index(fields=["owncast_user_id"], name="realtime_ow_owncast_897562_idx"),
                    models.Index(fields=["session", "created_at"], name="realtime_ow_session_78cf64_idx"),
                    models.Index(fields=["platform_user_id", "created_at"], name="realtime_ow_platfor_d8ccda_idx"),
                    models.Index(fields=["access_token_hash"], name="realtime_ow_access__ca349d_idx"),
                ],
            },
        ),
    ]
