# Generated by Django 5.1.6 on 2026-04-17 17:01

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def dedupe_chat_identities_by_platform_user(apps, schema_editor):
    OwncastChatIdentity = apps.get_model("realtime", "OwncastChatIdentity")
    duplicate_user_ids = (
        OwncastChatIdentity.objects.values("platform_user_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
        .values_list("platform_user_id", flat=True)
    )
    for platform_user_id in duplicate_user_ids:
        identity_ids = list(
            OwncastChatIdentity.objects.filter(platform_user_id=platform_user_id)
            .order_by("-updated_at", "-id")
            .values_list("id", flat=True)
        )
        stale_ids = identity_ids[1:]
        if stale_ids:
            OwncastChatIdentity.objects.filter(id__in=stale_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0020_owncastchatidentity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='owncastchatidentity',
            name='realtime_ow_platfor_d8ccda_idx',
        ),
        migrations.AddField(
            model_name='owncastchatidentity',
            name='access_token_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(dedupe_chat_identities_by_platform_user, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='owncastchatidentity',
            name='platform_user_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
