# Generated by Django 5.1.6 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtime", "0021_persistent_owncast_chat_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="owncastchatidentity",
            name="owncast_disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="owncastchatidentity",
            name="owncast_is_moderator",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="owncastchatidentity",
            name="owncast_timeout_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="owncastchatidentity",
            index=models.Index(fields=["owncast_timeout_until"], name="realtime_ow_owncast_817934_idx"),
        ),
    ]
