# Generated by Django 5.1.6 on 2026-02-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('osint', 'OSINT'), ('web_pentesting', 'Web Application Pentesting')], default='osint', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='launch_status',
            field=models.CharField(choices=[('live', 'Live'), ('coming_soon', 'Coming Soon')], default='live', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
