# Generated by Django 5.1.6 on 2026-02-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_category_course_launch_status_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
