# Generated by Django 5.1.6 on 2026-02-24 16:57

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_section_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.courses.models.lecture_video_upload_path),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_key',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
