# Generated by Django 5.1.6 on 2026-02-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_section_options_lecture_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='stream_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='stream_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lecture',
            name='stream_manifest_key',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='lecture',
            name='stream_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
