# Generated by Django 5.1.6 on 2026-02-24 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_liveclass_liveclassenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_published', 'category', 'level', 'launch_status'], name='courses_cou_is_publ_518503_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['instructor', 'is_published'], name='courses_cou_instruc_9a1002_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at'], name='courses_cou_created_51cadc_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'payment_status'], name='courses_enr_user_id_6f6ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'payment_status'], name='courses_enr_course__a1e8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'course', 'payment_status'], name='courses_enr_user_id_b3fc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['section', 'order'], name='courses_lec_section_bfe9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='lecture',
            index=models.Index(fields=['stream_status'], name='courses_lec_stream__139685_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['is_active', 'month_number', 'level'], name='courses_liv_is_acti_1f4f11_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['linked_course'], name='courses_liv_linked__6ecfe0_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclassenrollment',
            index=models.Index(fields=['user', 'created_at'], name='courses_liv_user_id_422326_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclassenrollment',
            index=models.Index(fields=['live_class', 'created_at'], name='courses_liv_live_cl_cbfed2_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['course', 'order'], name='courses_sec_course__60bff3_idx'),
        ),
    ]
