# Generated by Django 5.1.6 on 2026-03-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_courses_cou_is_publ_518503_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_file',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
