# Generated by Django 5.1.6 on 2026-03-06 08:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_thumbnail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
