# Generated by Django 5.1.6 on 2026-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_liveclass_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclassenrollment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
