# Generated by Django 5.1.6 on 2026-03-06 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_liveclassenrollment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicEnrollmentLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=24)),
                ('whatsapp_number', models.CharField(max_length=24)),
                ('message', models.TextField()),
                ('source_path', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('contacted', 'Contacted'), ('converted', 'Converted')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_enrollment_leads', to='courses.course')),
                ('live_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_enrollment_leads', to='courses.liveclass')),
            ],
            options={
                'verbose_name': 'Public Enrollment Lead',
                'verbose_name_plural': 'Public Enrollment Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='courses_pub_status_acffec_idx'), models.Index(fields=['email', 'created_at'], name='courses_pub_email_25efb4_idx'), models.Index(fields=['course', 'created_at'], name='courses_pub_course__a98359_idx'), models.Index(fields=['live_class', 'created_at'], name='courses_pub_live_cl_558e39_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('live_class__isnull', True)), models.Q(('course__isnull', True), ('live_class__isnull', False)), models.Q(('course__isnull', True), ('live_class__isnull', True)), _connector='OR'), name='courses_publicenrollmentlead_zero_or_one_target')],
            },
        ),
    ]
