# Generated by Django 5.1.6 on 2026-03-06 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='liveclassenrollment',
            index=models.Index(fields=['user', 'status'], name='courses_liv_user_id_a452bc_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclassenrollment',
            index=models.Index(fields=['live_class', 'status'], name='courses_liv_live_cl_35d0d9_idx'),
        ),
    ]
