# Generated by Django 5.1.6 on 2026-03-08 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_liveclassenrollment_courses_liv_user_id_a452bc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position_seconds', models.PositiveIntegerField(default=0)),
                ('max_position_seconds', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='courses.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_progress_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'updated_at'], name='courses_lec_user_id_4f909e_idx'), models.Index(fields=['lecture', 'updated_at'], name='courses_lec_lecture_4fe89e_idx'), models.Index(fields=['user', 'completed'], name='courses_lec_user_id_db4357_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'lecture'), name='courses_lectureprogress_unique_user_lecture')],
            },
        ),
    ]
