# Generated by Django 5.1.6 on 2026-04-01 00:00

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0016_course_about_the_course_course_course_overview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideVideo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "video_file",
                    models.FileField(
                        help_text="Upload MP4, M4V, MOV, or WEBM. Maximum size: 500 MB.",
                        upload_to=apps.courses.models.guide_video_upload_path,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Guide Video",
                "verbose_name_plural": "Guide Panel",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(fields=["is_published", "order"], name="courses_gui_is_publ_8f90f8_idx"),
                    models.Index(fields=["created_at"], name="courses_gui_created_83213f_idx"),
                ],
            },
        ),
    ]
