# Generated by Django 5.1.6 on 2026-04-04 20:35

import apps.courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_guidevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('resource_file', models.FileField(help_text='Upload TXT, PDF, PPT, PPTX, DOC, or DOCX files.', upload_to=apps.courses.models.lecture_resource_upload_path)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lecture Resource',
                'verbose_name_plural': 'Lecture Resources',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='guidevideo',
            new_name='courses_gui_is_publ_d3a209_idx',
            old_name='courses_gui_is_publ_8f90f8_idx',
        ),
        migrations.RenameIndex(
            model_name='guidevideo',
            new_name='courses_gui_created_72783d_idx',
            old_name='courses_gui_created_83213f_idx',
        ),
        migrations.AddField(
            model_name='lectureresource',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lecture'),
        ),
        migrations.AddIndex(
            model_name='lectureresource',
            index=models.Index(fields=['lecture', 'order'], name='courses_lec_lecture_44930e_idx'),
        ),
        migrations.AddIndex(
            model_name='lectureresource',
            index=models.Index(fields=['created_at'], name='courses_lec_created_f6bd94_idx'),
        ),
    ]
