# Generated by Codex on 2026-04-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_lectureresource_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LectureNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="courses.lecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="LectureQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("reviewed", "Reviewed"), ("answered", "Answered")],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="courses.lecture",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lecturenote",
            index=models.Index(fields=["user", "updated_at"], name="crs_note_user_upd_idx"),
        ),
        migrations.AddIndex(
            model_name="lecturenote",
            index=models.Index(fields=["lecture", "updated_at"], name="crs_note_lect_upd_idx"),
        ),
        migrations.AddConstraint(
            model_name="lecturenote",
            constraint=models.UniqueConstraint(fields=("user", "lecture"), name="crs_note_unique_user_lecture"),
        ),
        migrations.AddIndex(
            model_name="lecturequestion",
            index=models.Index(fields=["user", "created_at"], name="crs_q_user_created_idx"),
        ),
        migrations.AddIndex(
            model_name="lecturequestion",
            index=models.Index(fields=["lecture", "created_at"], name="crs_q_lect_created_idx"),
        ),
        migrations.AddIndex(
            model_name="lecturequestion",
            index=models.Index(fields=["status", "created_at"], name="crs_q_status_created_idx"),
        ),
    ]
