# Generated by Django 5.1.6 on 2026-04-12 16:28

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_lecturenote_lecturequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureresource',
            name='resource_url',
            field=models.URLField(blank=True, default='', help_text='Optional public http/https URL for an external lecture resource.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='lectureresource',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Upload TXT, PDF, PPT, PPTX, DOC, or DOCX files.', null=True, upload_to=apps.courses.models.lecture_resource_upload_path),
        ),
    ]
