# Generated by Codex on 2026-07-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_lectureresource_resource_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentRequestNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "channel",
                    models.CharField(
                        choices=[("whatsapp", "WhatsApp")],
                        default="whatsapp",
                        max_length=20,
                    ),
                ),
                ("destination", models.CharField(blank=True, default="", max_length=32)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("last_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_notifications",
                        to="courses.enrollment",
                    ),
                ),
                (
                    "live_class_enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_notifications",
                        to="courses.liveclassenrollment",
                    ),
                ),
                (
                    "public_lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_notifications",
                        to="courses.publicenrollmentlead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrollment Request Notification",
                "verbose_name_plural": "Enrollment Request Notifications",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["channel", "status", "created_at"], name="courses_enr_channel_e35fad_idx"),
                    models.Index(fields=["public_lead", "created_at"], name="courses_enr_public__b57d4c_idx"),
                    models.Index(fields=["enrollment", "created_at"], name="courses_enr_enrollm_15af34_idx"),
                    models.Index(fields=["live_class_enrollment", "created_at"], name="courses_enr_live_cl_3eb499_idx"),
                ],
            },
        ),
    ]
