# Generated by Django 5.1.6 on 2026-09-15 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_course_batch_course_batch_size_course_class_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_flagship',
            field=models.BooleanField(default=False, help_text="Show this course as the category's primary program."),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(condition=models.Q(('is_flagship', True)), fields=('category',), name='one_flagship_per_category'),
        ),
    ]
