# Generated by Django 5.1.6 on 2026-09-15 19:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_is_flagship_course_one_flagship_per_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch_size_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='course',
            name='bundle_access_days',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='course',
            name='bundle_installments',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='course',
            name='bundle_payment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='bundle_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='card_highlights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='card_subtitle',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='course',
            name='card_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='course',
            name='card_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
