# Generated by Django 5.1.6 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0027_course_batch_size_label_course_bundle_access_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="show_course_image",
            field=models.BooleanField(
                default=False,
                help_text="Show the optional course image only when it directly explains the program.",
            ),
        ),
    ]
