# Generated by Django 5.1.6 on 2026-09-20 05:25

from django.db import migrations, models
from django.utils import timezone

OSINT_SLUG = "osint-professional-training-batch-iv"

OSINT_PUBLIC_CURRICULUM = [
    {
        "title": "OSINT Foundations, Cybersecurity & Networking",
        "description": "Build the conceptual and ethical foundation required for professional public-source research.",
        "topics": [
            "OSINT: what it is, how it works and where it is used",
            "Cybersecurity and basic networking concepts for investigators",
            "Investigation methodology, source validation and evidence handling",
        ],
    },
    {
        "title": "Search Engine Intelligence",
        "description": "Move from basic searching to structured discovery across major search engines.",
        "topics": [
            "Google Dorking fundamentals and advanced operators",
            "Multi-stage Google Dorking research workflows",
            "Yandex Dorking and cross-engine verification",
            "Recording queries, sources and reproducible findings",
        ],
    },
    {
        "title": "Python Foundations for OSINT",
        "description": "Develop the basic programming literacy needed for repeatable research tasks.",
        "topics": [
            "Python basics I: values, variables and control flow",
            "Python basics II: collections, functions and files",
            "Python basics III: structured data and simple research automation",
        ],
    },
    {
        "title": "OSINT Tools, Directories & Telegram Research",
        "description": "Learn how to choose, validate and combine tools without treating tool output as verified evidence.",
        "topics": [
            "OSINT tools introduction and evaluation",
            "Advanced tool selection and research directories",
            "Telegram bots and public-channel research resources",
            "Cross-checking results and documenting tool limitations",
        ],
    },
    {
        "title": "Kali Linux Research Environment",
        "description": "Become familiar with a structured Linux workspace for authorized OSINT research.",
        "topics": [
            "Introduction to Kali Linux for investigators",
            "Filesystem, terminal and package-management essentials",
            "Organizing research artifacts and maintaining a clean workspace",
        ],
    },
    {
        "title": "Defensive Phishing Analysis",
        "description": "Study phishing as an investigation and defense problem, focusing on indicators and public infrastructure.",
        "topics": [
            "Phishing concepts, indicators and common delivery patterns",
            "Public-source analysis of domains, links and supporting infrastructure",
            "Evidence capture, risk communication and defensive reporting",
        ],
    },
    {
        "title": "Browser Hardening, Fingerprinting & Operational Privacy",
        "description": "Reduce avoidable research exposure and understand how browsers reveal investigator characteristics.",
        "topics": [
            "Browser hardening and safer research profiles",
            "Browser fingerprinting concepts and exposure analysis",
            "Firefox hardening and practical investigator OPSEC",
        ],
    },
    {
        "title": "Tor Architecture & Responsible Dark-Web Research",
        "description": "Understand anonymity technologies and the operational discipline required for lawful research.",
        "topics": [
            "Tor architecture and anonymity fundamentals",
            "Tails and Whonix research environments",
            "Responsible dark-web navigation and source evaluation",
            "Operational boundaries, evidence safety and research notes",
        ],
    },
    {
        "title": "Infrastructure, Attack Surface & Threat Intelligence",
        "description": "Map public organizational exposure and connect infrastructure findings into an intelligence picture.",
        "topics": [
            "Introduction to organizational OSINT and attack-surface mapping",
            "Organizational reconnaissance and public infrastructure correlation",
            "Threat-intelligence platforms and exposure monitoring",
            "API-assisted collection and repeatable monitoring workflows",
        ],
    },
    {
        "title": "CTF Practice, Case Analysis & Professional Reporting",
        "description": "Consolidate the program through guided challenges, casework and defensible reporting.",
        "topics": [
            "OSINT CTF walkthroughs and challenge methodology",
            "CTF training, examination and solution review",
            "Report analysis and target-focused reporting",
            "Building a clear methodology, evidence trail and final intelligence report",
        ],
    },
]


def enrich_osint_batch_four(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    Course.objects.filter(slug=OSINT_SLUG).update(
        card_summary=(
            "Build a complete OSINT workflow across search intelligence, research tools, "
            "operational privacy, infrastructure mapping, dark-web research, CTF practice "
            "and professional reporting."
        ),
        card_highlights=[
            "Beginner to advanced OSINT pathway",
            "Search, tools, infrastructure & dark-web research",
            "Browser OPSEC, reporting & Python foundations",
            "Practical CTF training and casework",
        ],
        description=(
            "Progress from OSINT foundations to advanced investigation workflows through "
            "search intelligence, research tools, operational security, infrastructure mapping, "
            "dark-web research, CTF practice and professional reporting."
        ),
        about_the_course=(
            "OSINT Professional Training Program Batch IV is a practical learning path built "
            "from the investigation methods taught across Al Syed Initiative classes. It connects "
            "foundational concepts with repeatable research methodology, safe tooling, source "
            "verification, operational privacy, organizational reconnaissance, challenge-based "
            "practice and evidence-led reporting."
        ),
        course_overview=(
            "Build a professional open-source intelligence workflow from the ground up. Begin "
            "with OSINT, cybersecurity and networking concepts, then develop search-engine "
            "research, Python foundations, tool selection, Kali Linux familiarity and defensive "
            "phishing analysis. Advance into browser hardening, fingerprinting, Tor architecture, "
            "anonymous research, organizational attack-surface mapping, threat-intelligence "
            "platforms and API-assisted workflows. Consolidate the program through CTF exercises, "
            "case analysis and structured reporting."
        ),
        what_you_will_learn=[
            "Apply a structured, ethical OSINT methodology from collection to reporting",
            "Use Google and Yandex search operators for targeted public-source research",
            "Select and validate OSINT tools, directories and Telegram research resources",
            "Build Python foundations for repeatable research and basic automation",
            "Work confidently with Kali Linux as an OSINT research environment",
            "Recognize phishing infrastructure and indicators through defensive analysis",
            "Harden browsers and manage fingerprinting, privacy and investigator OPSEC",
            "Understand Tor architecture, Tails, Whonix and responsible dark-web research",
            "Map organizational infrastructure, exposure and public attack surfaces",
            "Use threat-intelligence platforms, exposure monitoring and API-assisted research",
            "Solve OSINT CTF challenges and document evidence clearly",
            "Produce structured target, case and intelligence reports",
        ],
        expected_outcomes=[
            "Plan and execute a repeatable public-source investigation workflow",
            "Collect, verify and correlate findings across search engines and research tools",
            "Maintain safer operational practices during sensitive online research",
            "Map organizational infrastructure and identify publicly exposed assets",
            "Complete practical OSINT challenges using defensible evidence",
            "Present findings in a clear professional report with sources and methodology",
        ],
        course_card_features=[
            {
                "icon": "live",
                "title": "Live instructor-led classes",
                "description": "Follow the OSINT workflow with live demonstrations, guided practice and instructor feedback.",
            },
            {
                "icon": "chat",
                "title": "Live broadcast chat room",
                "description": "Ask questions and resolve research, tooling and methodology doubts during sessions.",
            },
            {
                "icon": "recording",
                "title": "Lifetime recorded access",
                "description": "Revisit class demonstrations, investigation workflows and supporting materials anytime.",
            },
            {
                "icon": "check",
                "title": "Practical CTF and casework",
                "description": "Apply research methods through guided challenges, walkthroughs and evidence analysis.",
            },
            {
                "icon": "certificate",
                "title": "Course completion certificate",
                "description": "Receive a certificate after meeting the published completion requirements.",
            },
            {
                "icon": "support",
                "title": "Investigation support",
                "description": "Get help with research methodology, reporting structure and responsible tool usage.",
            },
        ],
        public_curriculum=OSINT_PUBLIC_CURRICULUM,
        updated_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_publish_authorized_course_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='public_curriculum',
            field=models.JSONField(blank=True, default=list, help_text='Optional public course-detail roadmap. It is separate from lesson modules and never changes videos, progress, or student access.'),
        ),
        migrations.RunPython(
            enrich_osint_batch_four,
            migrations.RunPython.noop,
        ),
    ]
