# Generated by Django 5.1.6 on 2026-02-24 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_courses_cou_is_publ_518503_idx_and_more'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'course', 'razorpay_order_id'], name='payments_pa_user_id_78ff13_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', 'status', 'created_at'], name='payments_pa_user_id_35fb10_idx'),
        ),
    ]
