# Generated by Django 5.1.6 on 2026-07-28 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_plans_and_provisioning'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, default='', max_length=120)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('rejected', 'Rejected'), ('retry_queued', 'Retry queued'), ('failed', 'Failed')], default='received', max_length=24)),
                ('processing_note', models.CharField(blank=True, default='', max_length=500)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['status', 'received_at'], name='payments_pa_status_236c5c_idx'), models.Index(fields=['event_type', 'received_at'], name='payments_pa_event_t_d9bb34_idx')],
            },
        ),
    ]
