# Generated by Django 5.1.6 on 2026-09-15 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_course_batch_course_batch_size_course_class_length_and_more'),
        ('payments', '0009_paymentidempotencyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='courses.pentestingapplication'),
        ),
    ]
