# Generated by Django 5.1.6 on 2026-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='terms_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(choices=[('full', 'Full / lifetime'), ('monthly', 'Monthly installment'), ('bundle', '3-month bundle')], default='full', max_length=20),
        ),
    ]
