from django.urls import path

from .views import (
    CourseDetailView,
    CourseEnrollView,
    CourseListCreateView,
    CourseThumbnailView,
    GuideListView,
    GuideProtectedMediaView,
    GuideVideoView,
    InstructorCoursesView,
    LectureCreateView,
    LectureDetailView,
    LectureNoteView,
    LectureProgressView,
    LectureProtectedMediaView,
    LectureQuestionAdminListView,
    LectureQuestionListCreateView,
    LectureResourceDownloadView,
    LectureVideoView,
    LiveClassEnrollView,
    LiveClassListView,
    MyCoursesView,
    PublicEnrollmentLeadCreateView,
    SectionCreateView,
    SectionDetailView,
)

urlpatterns = [
    path("courses/", CourseListCreateView.as_view(), name="course-list-create"),
    path("courses/<int:pk>/", CourseDetailView.as_view(), name="course-detail"),
    path("courses/<int:pk>/thumbnail/", CourseThumbnailView.as_view(), name="course-thumbnail"),
    path("guides/", GuideListView.as_view(), name="guide-list"),
    path("guides/<int:pk>/video/", GuideVideoView.as_view(), name="guide-video"),
    path(
        "guides/<int:pk>/playback/<str:token>/<path:asset_path>",
        GuideProtectedMediaView.as_view(),
        name="guide-playback-asset",
    ),
    path("courses/enroll/", CourseEnrollView.as_view(), name="course-enroll"),
    path("sections/", SectionCreateView.as_view(), name="section-create"),
    path("sections/<int:pk>/", SectionDetailView.as_view(), name="section-detail"),
    path("lectures/", LectureCreateView.as_view(), name="lecture-create"),
    path("lectures/<int:pk>/", LectureDetailView.as_view(), name="lecture-detail"),
    path("lectures/<int:pk>/video/", LectureVideoView.as_view(), name="lecture-video"),
    path("lectures/<int:pk>/progress/", LectureProgressView.as_view(), name="lecture-progress"),
    path("lectures/<int:pk>/notes/", LectureNoteView.as_view(), name="lecture-notes"),
    path("lectures/<int:pk>/questions/", LectureQuestionListCreateView.as_view(), name="lecture-questions"),
    path("lecture-questions/", LectureQuestionAdminListView.as_view(), name="lecture-question-admin-list"),
    path(
        "lectures/<int:lecture_pk>/resources/<int:pk>/download/",
        LectureResourceDownloadView.as_view(),
        name="lecture-resource-download",
    ),
    path(
        "lectures/<int:pk>/playback/<str:token>/<path:asset_path>",
        LectureProtectedMediaView.as_view(),
        name="lecture-playback-asset",
    ),
    path("live-classes/", LiveClassListView.as_view(), name="live-class-list"),
    path("live-classes/enroll/", LiveClassEnrollView.as_view(), name="live-class-enroll"),
    path("enrollment-leads/", PublicEnrollmentLeadCreateView.as_view(), name="public-enrollment-lead-create"),
    path("my-courses/", MyCoursesView.as_view(), name="my-courses"),
    path("instructor/courses/", InstructorCoursesView.as_view(), name="instructor-courses"),
]
